# netlify.toml
# Production context:
[context.production]

  [[context.production.plugins]]
    package = "netlify-build-plugin-pushover"

      [context.production.plugins.inputs]
        successMessage="Success msg from Production ðŸ¥³"
        errorMessage="Error msg from Production ðŸš¨"


# Deploy Preview context:
[context.deploy-preview]

  [[context.deploy-preview.plugins]]
    package = "netlify-build-plugin-pushover"

      [context.deploy-preview.plugins.inputs]
        successMessage="Success msg from deploy preview ðŸ¥³"
        errorMessage="Error msg from deploy preview ðŸš¨"
